//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.IBLL.IService
{
    using System;
    using System.Collections.Generic;
    using App.Entity;
    using  App.Common.EFRepository;
    
    public partial interface ITB_USERSERVICE : IRepositoryBaseSql<TB_USER> 
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
